# SwiftLint
# https://github.com/realm/SwiftLint

# Rule Directory 
# https://realm.github.io/SwiftLint/rule-directory.html

included:
  - LottiePlayer/

# analyzer_rules:
#   - explicit_self
#   - unused_declaration
#   - unused_import

# disabled_rules:
#   - line_length
#   - nesting
#   - function_parameter_count

opt_in_rules:
  # Based on https://github.com/realm/SwiftLint/blob/075312af6e8b2ac527a02a725a51e55f65816a0f/.swiftlint.yml#L9-L74
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

# customized rules
# force_cast: warning
 
# cyclomatic_complexity: 
#   warning: 10
#   error: 15

# line_length: 
#   warning: 130
#   error: 200

# file_length:
#   warning: 300
#   error: 450

# type_body_length:
#   warning: 200
#   error: 300

# function_body_length:
#   warning: 40
#   error: 70

identifier_name:
  min_length: 1

file_name:
  excluded:
    - XXXX.swift

type_name:
  min_length: 4 # only warning
  max_length: 40 # only warning 
  excluded:
    - Key

number_separator:
  minimum_length: 5
